export const TECH_ICONS: Record<string, string> = {
  React: 'react',
  'Next.js': 'nextjs',
  TypeScript: 'typescript',
  'Tailwind CSS': 'tailwindcss',
  'Node.js': 'nodejs',
  AdonisJS: 'adonis',
  Express: 'expressjs',
  Prisma: 'prisma',
  PostgreSQL: 'postgresql',
  MySQL: 'mysql',
  Redis: 'redis',
  Flutter: 'flutter',
  Dart: 'dart',
  Python: 'python',
  Selenium: 'selenium',
  Git: 'git',
  GitHub: 'github',
  Docker: 'docker',
  'AWS (S3, Amplify)': 'aws',
  Figma: 'figma',
  Postman: 'postman',
  Fastify: 'fastify',
  'React Native': 'reactnative',
  Expo: 'expo',
  n8n: 'n8n',
}
